version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    restart: always
    container_name: selenium-hub
    ports:
      - "4444:4444"

  selenium-node-chrome:
    image: selenium/node-chrome:3.141.59-zirconium
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  selenium-side-runner:
    build: .
    depends_on:
      - selenium-node-chrome
    volumes:
      - './sides:/sides'
      - './out:/root/out'

